### ISSUE TITLE
Does the Chrome VNC dockerfile need to start X or ratpoison explicitly?

### ISSUE THREAD

**Issue by skijit** [theonemule/dockercon-demos#1]
Running the container on WSL2 and although I can connect to VNC through my local browser, it's just a blank black screen.  If I `ps -ef` inside the container, I don't see ratpoison, X, or chrome running.  Wondering if the CMD needs some additional instructions?

Very interesting DockerCon talk, btw.  Thanks for this material.

**Comment by theonemule** [comment]
It shouldn't have to... this was working at DockerCon, but I haven't test it in a while. I would have to try it again. Because there are so many dependencies, it can make it a bit fragile.

**Comment by skijit** [comment]
I changed the base image from `ubuntu` to `ubuntu:18.04` and now it works.  I'd issue a PR, but I'm not entirely convinced that was the root cause.  Closing the issue- thanks again!
